### ISSUE TITLE
[EPIC]Тестирование проблемы и переработка InfectionZone для всех карт

### ISSUE THREAD

**Issue by DeusExMachinaTeam** [DeusExMachinaTeam/EM-CommunityPatch#225]
В процессе стрима Павлика появились подозрения что и так требущие переработки инфекшзоны, стали работать ещё хуже - ещё реже спавнить врагов "там где нужно". Для исправления проблемы нужно две вещи:

- [ ] понять в чём отличие спавна между стоковой игрой и компатчем
(благодаря любезно подготовленной тест-карте от @lineisover, спросить подобнее можно в Discord)

независимо от результов и фиксов по первому пункту:
- [x] пересмотреть инфекшены для Края
А именно понять как можно поменять их "форму" и дропаут-точки (точки спавна врагов в пределах зон) для того чтобы враги не спавнились на другом конце карты и не деспавнились сразу, а вместо этого спавнились ближе к игроку, предпочительно в логичных точках по пути к зонам интереса на карте и из них
- [ ] применить это к остальным картам после оттачивания техники на Крае

Предполагается что лучше всего для начала изобразить стандартные инфекшены и их дропауты на 2D картинке карты, чтобы понять что с ними не так глобально

Список всех карт для правки:

Первый регион:
- [x] Край - гном сделал в тестовом билде, играется хорошо. Надо смерджить.
- [x] #323
- [x] #324
- [x] #325

Второй регион:
- [x] #326
- [x] #327

Третий регион:
- [x] #328
- [x] #329

Четвертый регион:
- [x] #330 
- [x] #331 

Желательно сделать хотя бы для первого региона.
