### ISSUE TITLE
Упрощение dynamicscene.xml для крупных карт

### ISSUE THREAD

**Issue by Zvetkov** [DeusExMachinaTeam/EM-CommunityPatch#8]
Нужно определить для каких карт это **необходимо**, и решить что именно можно безопасно убрать или заменить для повышения стабильности крупных карт. Не нужно это делать для всех карт, только для тех, для которых у нас возникают подозрения что вылеты вызваны слишком большим количеством динамических объектов.

Для работы над отдельными картам лучше создать новые issues и линкануть их сюда с помощью синтаксиса #<номер_этого_issue>

- [ ] #103 - Упрощение dynamicscene.xml для r1m2 (Риджин)
- [ ] #102 - Упрощение dynamicscene.xml для r1m3 (Фатерлянд)
- [ ] #104 - Упрощение dynamicscene.xml для r1m3 (Либриума)

**Comment by DeusExMachinaTeam** [comment]
Согласно текущим данным в изменении нет необходимости, вылеты вызваны другим
Фатерлянд единственная карта для которой были внесены изменения

**Comment by lineisover** [comment]
И я этим занимался.....
